apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-test-demo.fullname" . }}-svc
  labels:
    app: {{ template "prometheus-test-demo.fullname" . }}
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
    - port: 8998
      targetPort: 8998
      protocol: TCP
      name: tcp
  selector:
    app: {{ template "prometheus-test-demo.fullname" . }}

