apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: {{ include "prometheus-test-demo.fullname" . }}
  name: {{ include "prometheus-test-demo.fullname" . }}
spec:
  endpoints:
  - interval: 30s
    port: tcp
    path: /actuator/prometheus
    scheme: 'http'
  selector:
    matchLabels:
      app: {{ template "prometheus-test-demo.fullname" . }}
  namespaceSelector:
    matchNames:
    - {{  .Release.Namespace }}
